Task 7.2
Mitoschka/Homework.C-sharp-second-term pull request #14
Opened 2020-04-06 13:51 UTC by Michael-200

2020-04-17 09:28 UTC, yurii-litvinov requested changes

2020-04-17 09:28 UTC, yurii-litvinov commented on Task 7.2/Analog Clock/Form1.cs
> +    public partial class Form1 : Form
Form1 --- плохое имя класса

2020-04-17 09:28 UTC, yurii-litvinov commented on Task 7.2/Analog Clock/Form1.cs
> +namespace Analog_Clock
Пространства имён называются без подчёркиваний, просто AnalogClock

2020-04-17 09:28 UTC, yurii-litvinov commented on Task 7.2/Analog Clock/Form1.cs
> +        int count = 0;
private

2020-04-17 09:28 UTC, yurii-litvinov commented on Task 7.2/Analog Clock/Form1.cs
> +        Bitmap back, hour, minute, dot, second;
Объявления должны быть по одному на строке

2020-04-17 09:28 UTC, yurii-litvinov commented on Task 7.2/Analog Clock/Form1.cs
> +            PrivateFontCollection fontCollection = new PrivateFontCollection();
vat

2020-04-17 09:28 UTC, yurii-litvinov commented on Task 7.2/Analog Clock/Form1.cs
> +        }
Это не нужно :)

2020-04-17 09:28 UTC, yurii-litvinov commented on Task 7.2/Analog Clock/Form1.cs
> +        private Bitmap rotateImage(Bitmap rotateMe, float angle)
Методы с заглавной называются

2020-04-17 09:28 UTC, yurii-litvinov commented on Task 7.2/Analog Clock/Form1.cs
> +            using(Graphics g = Graphics.FromImage(rotatedImage))
Пробела не хватает

2020-04-17 09:28 UTC, yurii-litvinov commented on Task 7.2/Analog Clock/Form1.cs
> +            Bitmap rotatedImage = new Bitmap(rotateMe.Width, rotateMe.Height);
var

2020-04-17 09:28 UTC, yurii-litvinov commented on Task 7.2/Analog Clock/Form1.cs
> +using System.Windows.Forms;
Куча ненужных using-ов, надо почистить во всём проекте (благо Visual Studio умеет делать это автоматически)

2020-04-17 09:28 UTC, yurii-litvinov commented on Task 7.2/Analog Clock/Form1.cs
> +            back = new Bitmap(".\\newBack.png");
У меня такого нету, не запускается

2020-04-18 18:55 UTC, Michael-200 commented
k

2020-04-18 18:56 UTC, closed without merging